### ISSUE TITLE
npm run build失败

### ISSUE THREAD

**Issue by chenming7583** [peterchenhdu/webbf#5]
verbose stack Error: Invalid version: "v0.1-alpha"
4 verbose stack     at Object.fixVersionField (D:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:191:13)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (D:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
4 verbose stack     at final (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:349:5)
4 verbose stack     at then (D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:426:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)

**Comment by chenming7583** [comment]
修改一下版本就可以编译了

**Comment by xiaoyi62** [comment]
修改哪个版本？

**Comment by chenming7583** [comment]
Package.json

 

发件人: bounces+848413-639c-20chenming08=163.com@sgmail.github.com [mailto:bounces+848413-639c-20chenming08=163.com@sgmail.github.com] 代表 xiaoyi62
发送时间: 2017年2月13日 16:07
收件人: peterchenhdu/webbf <webbf@noreply.github.com>
抄送: chenming7583 <20chenming08@163.com>; Author <author@noreply.github.com>
主题: Re: [peterchenhdu/webbf] npm run build失败 (#5)

 

修改哪个版本？

**Comment by gujunhk** [comment]
因为版本号是x.y-alpha的格式了，不是通用的x.y.z。有两种方式解决：
1. 把版本号改为0.1.0
2. `npm install semver`
